<?php

/**
 * Copyright (c) 2016, 2024, 5 Mode
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither 5 Mode nor the names of its contributors 
 *       may be used to endorse or promote products derived from this software 
 *       without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * const.php.inc
 * 
 * John Help PHP constant file.
 *
 * @author Daniele Bonini <my25mb@aol.com>
 * @copyrights (c) 2021, 2024, 5 Mode     
 */

if (!defined("PHP_BR")) {
  define('PHP_BR', "<br>");
}
if (!defined("PHP_CN")) {
  define('PHP_CN', "zh-CN");
}
if (!defined("PHP_EN")) {
  define('PHP_EN', "en-US");
}
if (!defined("PHP_ES")) {
  define('PHP_ES', "es-ES");
}
if (!defined("PHP_FR")) {
  define('PHP_FR', "fr-FR");
}
if (!defined("PHP_HYPHEN")) {
  define('PHP_HYPHEN', "-");
}
if (!defined("PHP_IT")) {
  define('PHP_IT', "it-IT");
}
if (!defined("PHP_PIPE")) {
  define('PHP_PIPE', "|");
}
if (!defined("PHP_FILE_PIPE")) {
  define('PHP_FILE_PIPE', ">");
}
if (!defined("PHP_SLASH")) {
  define('PHP_SLASH', "/");
}
if (!defined("PHP_SPACE")) {
  define('PHP_SPACE', " ");
}
if (!defined("PHP_STR")) {
  define('PHP_STR', "");
}
if (!defined("PHP_TILDE")) {
  define('PHP_TILDE', "~");
}
if (!defined("PHP_UNDERSCORE")) {
  define('PHP_UNDERSCORE', "_");
}
if (!defined("PHP_UPLOAD_ERR_OK")) {
  define('PHP_UPLOAD_ERR_OK', 0);
}
if (!defined("PHP_UPLOAD_ERR_INI_SIZE")) {
  define('PHP_UPLOAD_ERR_INI_SIZE', 1);
}
if (!defined("PHP_UPLOAD_ERR_FORM_SIZE")) {
  define('PHP_UPLOAD_ERR_FORM_SIZE', 2);
}
if (!defined("PHP_UPLOAD_ERR_PARTIAL")) {
  define('PHP_UPLOAD_ERR_PARTIAL', 3);
}
if (!defined("PHP_UPLOAD_ERR_NO_FILE")) {
  define('PHP_UPLOAD_ERR_NO_FILE', 4);
}
if (!defined("PHP_UPLOAD_ERR_NO_TMP_DIR")) {
  define('PHP_UPLOAD_ERR_NO_TMP_DIR', 6);
}
if (!defined("PHP_UPLOAD_ERR_CANT_WRITE")) {
  define('PHP_UPLOAD_ERR_CANT_WRITE', 7);
}
if (!defined("PHP_UPLOAD_ERR_EXTENSION")) {
  define('PHP_UPLOAD_ERR_EXTENSION', 8);
}
